name: Publish FluentSignals.SignalBus

on:
  push:
    branches:
      - main
    paths:
      - 'Libs/FluentSignals.SignalBus/**'
      - 'Directory.Build.props'
      - '.github/workflows/publish-fluentsignals-signalbus.yml'
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (leave empty to use Directory.Build.props version)'
        required: false
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Libs/FluentSignals.SignalBus/FluentSignals.SignalBus.csproj

    - name: Build
      run: dotnet build Libs/FluentSignals.SignalBus/FluentSignals.SignalBus.csproj --configuration Release --no-restore

    - name: Extract version
      id: extract_version
      run: |
        if [ -n "${{ github.event.inputs.version_override }}" ]; then
          VERSION="${{ github.event.inputs.version_override }}"
        else
          # Check if SignalBus has its own version first
          SIGNALBUS_VERSION=$(grep '<Version>' Libs/FluentSignals.SignalBus/FluentSignals.SignalBus.csproj | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/' | head -n 1)
          if [ -n "$SIGNALBUS_VERSION" ]; then
            VERSION="$SIGNALBUS_VERSION"
          else
            VERSION=$(grep '<Version>' Directory.Build.props | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/')
          fi
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Pack FluentSignals.SignalBus
      run: dotnet pack Libs/FluentSignals.SignalBus/FluentSignals.SignalBus.csproj --configuration Release --no-build -p:PackageVersion=${{ steps.extract_version.outputs.VERSION }} --output ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/FluentSignals.SignalBus.${{ steps.extract_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate