name: Publish FluentSignals.Http

on:
  push:
    branches:
      - main
    paths:
      - 'Libs/FluentSignals.Http/**'
      - 'Directory.Build.props'
      - '.github/workflows/publish-fluentsignals-http.yml'
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (leave empty to use Directory.Build.props version)'
        required: false
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Libs/FluentSignals.Http/FluentSignals.Http.csproj

    - name: Build
      run: dotnet build Libs/FluentSignals.Http/FluentSignals.Http.csproj --configuration Release --no-restore

    - name: Test Http
      continue-on-error: true
      run: dotnet test Libs/FluentSignals.Http.Tests/FluentSignals.Http.Tests.csproj --configuration Release --no-build --verbosity normal || echo "::warning::Tests failed but continuing with publish"

    - name: Extract version
      id: extract_version
      run: |
        if [ -n "${{ github.event.inputs.version_override }}" ]; then
          VERSION="${{ github.event.inputs.version_override }}"
        else
          VERSION=$(grep '<Version>' Directory.Build.props | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/')
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Pack FluentSignals.Http
      run: dotnet pack Libs/FluentSignals.Http/FluentSignals.Http.csproj --configuration Release --no-build -p:PackageVersion=${{ steps.extract_version.outputs.VERSION }} --output ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/FluentSignals.Http.${{ steps.extract_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate